/**
 */
package org.eclipse.sensinact.studio.language.sensinact.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.eclipse.sensinact.studio.language.sensinact.util.SensinactAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SensinactItemProviderAdapterFactory extends SensinactAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SensinactItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.Sensinact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SensinactItemProvider sensinactItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.Sensinact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSensinactAdapter() {
		if (sensinactItemProvider == null) {
			sensinactItemProvider = new SensinactItemProvider(this);
		}

		return sensinactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_SENSINACT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_SENSINACTItemProvider dsL_SENSINACTItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_SENSINACT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_SENSINACTAdapter() {
		if (dsL_SENSINACTItemProvider == null) {
			dsL_SENSINACTItemProvider = new DSL_SENSINACTItemProvider(this);
		}

		return dsL_SENSINACTItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_FLAG_AUTOSTART} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_FLAG_AUTOSTARTItemProvider dsL_FLAG_AUTOSTARTItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_FLAG_AUTOSTART}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_FLAG_AUTOSTARTAdapter() {
		if (dsL_FLAG_AUTOSTARTItemProvider == null) {
			dsL_FLAG_AUTOSTARTItemProvider = new DSL_FLAG_AUTOSTARTItemProvider(this);
		}

		return dsL_FLAG_AUTOSTARTItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ResourceItemProvider dsL_ResourceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ResourceAdapter() {
		if (dsL_ResourceItemProvider == null) {
			dsL_ResourceItemProvider = new DSL_ResourceItemProvider(this);
		}

		return dsL_ResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_On} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_OnItemProvider dsL_OnItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_On}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_OnAdapter() {
		if (dsL_OnItemProvider == null) {
			dsL_OnItemProvider = new DSL_OnItemProvider(this);
		}

		return dsL_OnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ECA_STATEMENT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ECA_STATEMENTItemProvider dsL_ECA_STATEMENTItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ECA_STATEMENT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ECA_STATEMENTAdapter() {
		if (dsL_ECA_STATEMENTItemProvider == null) {
			dsL_ECA_STATEMENTItemProvider = new DSL_ECA_STATEMENTItemProvider(this);
		}

		return dsL_ECA_STATEMENTItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_IfDo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_IfDoItemProvider dsL_IfDoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_IfDo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_IfDoAdapter() {
		if (dsL_IfDoItemProvider == null) {
			dsL_IfDoItemProvider = new DSL_IfDoItemProvider(this);
		}

		return dsL_IfDoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ElseIfDo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ElseIfDoItemProvider dsL_ElseIfDoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ElseIfDo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ElseIfDoAdapter() {
		if (dsL_ElseIfDoItemProvider == null) {
			dsL_ElseIfDoItemProvider = new DSL_ElseIfDoItemProvider(this);
		}

		return dsL_ElseIfDoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ElseDo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ElseDoItemProvider dsL_ElseDoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ElseDo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ElseDoAdapter() {
		if (dsL_ElseDoItemProvider == null) {
			dsL_ElseDoItemProvider = new DSL_ElseDoItemProvider(this);
		}

		return dsL_ElseDoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_REF} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_REFItemProvider dsL_REFItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_REF}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_REFAdapter() {
		if (dsL_REFItemProvider == null) {
			dsL_REFItemProvider = new DSL_REFItemProvider(this);
		}

		return dsL_REFItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_REF_CONDITION} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_REF_CONDITIONItemProvider dsL_REF_CONDITIONItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_REF_CONDITION}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_REF_CONDITIONAdapter() {
		if (dsL_REF_CONDITIONItemProvider == null) {
			dsL_REF_CONDITIONItemProvider = new DSL_REF_CONDITIONItemProvider(this);
		}

		return dsL_REF_CONDITIONItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_STATEMENT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_STATEMENTItemProvider dsL_CEP_STATEMENTItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_STATEMENT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_STATEMENTAdapter() {
		if (dsL_CEP_STATEMENTItemProvider == null) {
			dsL_CEP_STATEMENTItemProvider = new DSL_CEP_STATEMENTItemProvider(this);
		}

		return dsL_CEP_STATEMENTItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_AFTER} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_AFTERItemProvider dsL_CEP_AFTERItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_AFTER}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_AFTERAdapter() {
		if (dsL_CEP_AFTERItemProvider == null) {
			dsL_CEP_AFTERItemProvider = new DSL_CEP_AFTERItemProvider(this);
		}

		return dsL_CEP_AFTERItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_BEFORE} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_BEFOREItemProvider dsL_CEP_BEFOREItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_BEFORE}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_BEFOREAdapter() {
		if (dsL_CEP_BEFOREItemProvider == null) {
			dsL_CEP_BEFOREItemProvider = new DSL_CEP_BEFOREItemProvider(this);
		}

		return dsL_CEP_BEFOREItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_COINCIDE} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_COINCIDEItemProvider dsL_CEP_COINCIDEItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_COINCIDE}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_COINCIDEAdapter() {
		if (dsL_CEP_COINCIDEItemProvider == null) {
			dsL_CEP_COINCIDEItemProvider = new DSL_CEP_COINCIDEItemProvider(this);
		}

		return dsL_CEP_COINCIDEItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_MIN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_MINItemProvider dsL_CEP_MINItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_MIN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_MINAdapter() {
		if (dsL_CEP_MINItemProvider == null) {
			dsL_CEP_MINItemProvider = new DSL_CEP_MINItemProvider(this);
		}

		return dsL_CEP_MINItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_MAX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_MAXItemProvider dsL_CEP_MAXItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_MAX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_MAXAdapter() {
		if (dsL_CEP_MAXItemProvider == null) {
			dsL_CEP_MAXItemProvider = new DSL_CEP_MAXItemProvider(this);
		}

		return dsL_CEP_MAXItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_AVG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_AVGItemProvider dsL_CEP_AVGItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_AVG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_AVGAdapter() {
		if (dsL_CEP_AVGItemProvider == null) {
			dsL_CEP_AVGItemProvider = new DSL_CEP_AVGItemProvider(this);
		}

		return dsL_CEP_AVGItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_SUM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_SUMItemProvider dsL_CEP_SUMItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_SUM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_SUMAdapter() {
		if (dsL_CEP_SUMItemProvider == null) {
			dsL_CEP_SUMItemProvider = new DSL_CEP_SUMItemProvider(this);
		}

		return dsL_CEP_SUMItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_COUNT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_COUNTItemProvider dsL_CEP_COUNTItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_COUNT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_COUNTAdapter() {
		if (dsL_CEP_COUNTItemProvider == null) {
			dsL_CEP_COUNTItemProvider = new DSL_CEP_COUNTItemProvider(this);
		}

		return dsL_CEP_COUNTItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_DURATIONItemProvider dsL_CEP_DURATIONItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_DURATIONAdapter() {
		if (dsL_CEP_DURATIONItemProvider == null) {
			dsL_CEP_DURATIONItemProvider = new DSL_CEP_DURATIONItemProvider(this);
		}

		return dsL_CEP_DURATIONItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION_MIN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_DURATION_MINItemProvider dsL_CEP_DURATION_MINItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION_MIN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_DURATION_MINAdapter() {
		if (dsL_CEP_DURATION_MINItemProvider == null) {
			dsL_CEP_DURATION_MINItemProvider = new DSL_CEP_DURATION_MINItemProvider(this);
		}

		return dsL_CEP_DURATION_MINItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION_SEC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_CEP_DURATION_SECItemProvider dsL_CEP_DURATION_SECItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_CEP_DURATION_SEC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_CEP_DURATION_SECAdapter() {
		if (dsL_CEP_DURATION_SECItemProvider == null) {
			dsL_CEP_DURATION_SECItemProvider = new DSL_CEP_DURATION_SECItemProvider(this);
		}

		return dsL_CEP_DURATION_SECItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ListActions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ListActionsItemProvider dsL_ListActionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ListActions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ListActionsAdapter() {
		if (dsL_ListActionsItemProvider == null) {
			dsL_ListActionsItemProvider = new DSL_ListActionsItemProvider(this);
		}

		return dsL_ListActionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ResourceAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ResourceActionItemProvider dsL_ResourceActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ResourceAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ResourceActionAdapter() {
		if (dsL_ResourceActionItemProvider == null) {
			dsL_ResourceActionItemProvider = new DSL_ResourceActionItemProvider(this);
		}

		return dsL_ResourceActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ListParam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ListParamItemProvider dsL_ListParamItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_ListParam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ListParamAdapter() {
		if (dsL_ListParamItemProvider == null) {
			dsL_ListParamItemProvider = new DSL_ListParamItemProvider(this);
		}

		return dsL_ListParamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ExpressionItemProvider dsL_ExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_ExpressionAdapter() {
		if (dsL_ExpressionItemProvider == null) {
			dsL_ExpressionItemProvider = new DSL_ExpressionItemProvider(this);
		}

		return dsL_ExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Or} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_OrItemProvider dsL_Expression_OrItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Or}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_OrAdapter() {
		if (dsL_Expression_OrItemProvider == null) {
			dsL_Expression_OrItemProvider = new DSL_Expression_OrItemProvider(this);
		}

		return dsL_Expression_OrItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_And} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_AndItemProvider dsL_Expression_AndItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_And}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_AndAdapter() {
		if (dsL_Expression_AndItemProvider == null) {
			dsL_Expression_AndItemProvider = new DSL_Expression_AndItemProvider(this);
		}

		return dsL_Expression_AndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Diff} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_DiffItemProvider dsL_Expression_DiffItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Diff}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_DiffAdapter() {
		if (dsL_Expression_DiffItemProvider == null) {
			dsL_Expression_DiffItemProvider = new DSL_Expression_DiffItemProvider(this);
		}

		return dsL_Expression_DiffItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Equal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_EqualItemProvider dsL_Expression_EqualItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Equal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_EqualAdapter() {
		if (dsL_Expression_EqualItemProvider == null) {
			dsL_Expression_EqualItemProvider = new DSL_Expression_EqualItemProvider(this);
		}

		return dsL_Expression_EqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Larger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_LargerItemProvider dsL_Expression_LargerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Larger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_LargerAdapter() {
		if (dsL_Expression_LargerItemProvider == null) {
			dsL_Expression_LargerItemProvider = new DSL_Expression_LargerItemProvider(this);
		}

		return dsL_Expression_LargerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Larger_Equal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_Larger_EqualItemProvider dsL_Expression_Larger_EqualItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Larger_Equal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_Larger_EqualAdapter() {
		if (dsL_Expression_Larger_EqualItemProvider == null) {
			dsL_Expression_Larger_EqualItemProvider = new DSL_Expression_Larger_EqualItemProvider(this);
		}

		return dsL_Expression_Larger_EqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Smaller} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_SmallerItemProvider dsL_Expression_SmallerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Smaller}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_SmallerAdapter() {
		if (dsL_Expression_SmallerItemProvider == null) {
			dsL_Expression_SmallerItemProvider = new DSL_Expression_SmallerItemProvider(this);
		}

		return dsL_Expression_SmallerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Smaller_Equal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_Smaller_EqualItemProvider dsL_Expression_Smaller_EqualItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Smaller_Equal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_Smaller_EqualAdapter() {
		if (dsL_Expression_Smaller_EqualItemProvider == null) {
			dsL_Expression_Smaller_EqualItemProvider = new DSL_Expression_Smaller_EqualItemProvider(this);
		}

		return dsL_Expression_Smaller_EqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Plus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_PlusItemProvider dsL_Expression_PlusItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Plus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_PlusAdapter() {
		if (dsL_Expression_PlusItemProvider == null) {
			dsL_Expression_PlusItemProvider = new DSL_Expression_PlusItemProvider(this);
		}

		return dsL_Expression_PlusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Minus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_MinusItemProvider dsL_Expression_MinusItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Minus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_MinusAdapter() {
		if (dsL_Expression_MinusItemProvider == null) {
			dsL_Expression_MinusItemProvider = new DSL_Expression_MinusItemProvider(this);
		}

		return dsL_Expression_MinusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Multiplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_MultiplicationItemProvider dsL_Expression_MultiplicationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Multiplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_MultiplicationAdapter() {
		if (dsL_Expression_MultiplicationItemProvider == null) {
			dsL_Expression_MultiplicationItemProvider = new DSL_Expression_MultiplicationItemProvider(this);
		}

		return dsL_Expression_MultiplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Division} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_DivisionItemProvider dsL_Expression_DivisionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Division}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_DivisionAdapter() {
		if (dsL_Expression_DivisionItemProvider == null) {
			dsL_Expression_DivisionItemProvider = new DSL_Expression_DivisionItemProvider(this);
		}

		return dsL_Expression_DivisionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Modulo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_ModuloItemProvider dsL_Expression_ModuloItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Modulo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_ModuloAdapter() {
		if (dsL_Expression_ModuloItemProvider == null) {
			dsL_Expression_ModuloItemProvider = new DSL_Expression_ModuloItemProvider(this);
		}

		return dsL_Expression_ModuloItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Number} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Object_NumberItemProvider dsL_Object_NumberItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Number}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Object_NumberAdapter() {
		if (dsL_Object_NumberItemProvider == null) {
			dsL_Object_NumberItemProvider = new DSL_Object_NumberItemProvider(this);
		}

		return dsL_Object_NumberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_String} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Object_StringItemProvider dsL_Object_StringItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_String}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Object_StringAdapter() {
		if (dsL_Object_StringItemProvider == null) {
			dsL_Object_StringItemProvider = new DSL_Object_StringItemProvider(this);
		}

		return dsL_Object_StringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Boolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Object_BooleanItemProvider dsL_Object_BooleanItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Boolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Object_BooleanAdapter() {
		if (dsL_Object_BooleanItemProvider == null) {
			dsL_Object_BooleanItemProvider = new DSL_Object_BooleanItemProvider(this);
		}

		return dsL_Object_BooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Ref} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Object_RefItemProvider dsL_Object_RefItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Object_Ref}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Object_RefAdapter() {
		if (dsL_Object_RefItemProvider == null) {
			dsL_Object_RefItemProvider = new DSL_Object_RefItemProvider(this);
		}

		return dsL_Object_RefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Negate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_Expression_NegateItemProvider dsL_Expression_NegateItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Negate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDSL_Expression_NegateAdapter() {
		if (dsL_Expression_NegateItemProvider == null) {
			dsL_Expression_NegateItemProvider = new DSL_Expression_NegateItemProvider(this);
		}

		return dsL_Expression_NegateItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (sensinactItemProvider != null) sensinactItemProvider.dispose();
		if (dsL_SENSINACTItemProvider != null) dsL_SENSINACTItemProvider.dispose();
		if (dsL_FLAG_AUTOSTARTItemProvider != null) dsL_FLAG_AUTOSTARTItemProvider.dispose();
		if (dsL_ResourceItemProvider != null) dsL_ResourceItemProvider.dispose();
		if (dsL_OnItemProvider != null) dsL_OnItemProvider.dispose();
		if (dsL_ECA_STATEMENTItemProvider != null) dsL_ECA_STATEMENTItemProvider.dispose();
		if (dsL_IfDoItemProvider != null) dsL_IfDoItemProvider.dispose();
		if (dsL_ElseIfDoItemProvider != null) dsL_ElseIfDoItemProvider.dispose();
		if (dsL_ElseDoItemProvider != null) dsL_ElseDoItemProvider.dispose();
		if (dsL_REFItemProvider != null) dsL_REFItemProvider.dispose();
		if (dsL_REF_CONDITIONItemProvider != null) dsL_REF_CONDITIONItemProvider.dispose();
		if (dsL_CEP_STATEMENTItemProvider != null) dsL_CEP_STATEMENTItemProvider.dispose();
		if (dsL_CEP_AFTERItemProvider != null) dsL_CEP_AFTERItemProvider.dispose();
		if (dsL_CEP_BEFOREItemProvider != null) dsL_CEP_BEFOREItemProvider.dispose();
		if (dsL_CEP_COINCIDEItemProvider != null) dsL_CEP_COINCIDEItemProvider.dispose();
		if (dsL_CEP_MINItemProvider != null) dsL_CEP_MINItemProvider.dispose();
		if (dsL_CEP_MAXItemProvider != null) dsL_CEP_MAXItemProvider.dispose();
		if (dsL_CEP_AVGItemProvider != null) dsL_CEP_AVGItemProvider.dispose();
		if (dsL_CEP_SUMItemProvider != null) dsL_CEP_SUMItemProvider.dispose();
		if (dsL_CEP_COUNTItemProvider != null) dsL_CEP_COUNTItemProvider.dispose();
		if (dsL_CEP_DURATIONItemProvider != null) dsL_CEP_DURATIONItemProvider.dispose();
		if (dsL_CEP_DURATION_MINItemProvider != null) dsL_CEP_DURATION_MINItemProvider.dispose();
		if (dsL_CEP_DURATION_SECItemProvider != null) dsL_CEP_DURATION_SECItemProvider.dispose();
		if (dsL_ListActionsItemProvider != null) dsL_ListActionsItemProvider.dispose();
		if (dsL_ResourceActionItemProvider != null) dsL_ResourceActionItemProvider.dispose();
		if (dsL_ListParamItemProvider != null) dsL_ListParamItemProvider.dispose();
		if (dsL_ExpressionItemProvider != null) dsL_ExpressionItemProvider.dispose();
		if (dsL_Expression_OrItemProvider != null) dsL_Expression_OrItemProvider.dispose();
		if (dsL_Expression_AndItemProvider != null) dsL_Expression_AndItemProvider.dispose();
		if (dsL_Expression_DiffItemProvider != null) dsL_Expression_DiffItemProvider.dispose();
		if (dsL_Expression_EqualItemProvider != null) dsL_Expression_EqualItemProvider.dispose();
		if (dsL_Expression_LargerItemProvider != null) dsL_Expression_LargerItemProvider.dispose();
		if (dsL_Expression_Larger_EqualItemProvider != null) dsL_Expression_Larger_EqualItemProvider.dispose();
		if (dsL_Expression_SmallerItemProvider != null) dsL_Expression_SmallerItemProvider.dispose();
		if (dsL_Expression_Smaller_EqualItemProvider != null) dsL_Expression_Smaller_EqualItemProvider.dispose();
		if (dsL_Expression_PlusItemProvider != null) dsL_Expression_PlusItemProvider.dispose();
		if (dsL_Expression_MinusItemProvider != null) dsL_Expression_MinusItemProvider.dispose();
		if (dsL_Expression_MultiplicationItemProvider != null) dsL_Expression_MultiplicationItemProvider.dispose();
		if (dsL_Expression_DivisionItemProvider != null) dsL_Expression_DivisionItemProvider.dispose();
		if (dsL_Expression_ModuloItemProvider != null) dsL_Expression_ModuloItemProvider.dispose();
		if (dsL_Object_NumberItemProvider != null) dsL_Object_NumberItemProvider.dispose();
		if (dsL_Object_StringItemProvider != null) dsL_Object_StringItemProvider.dispose();
		if (dsL_Object_BooleanItemProvider != null) dsL_Object_BooleanItemProvider.dispose();
		if (dsL_Object_RefItemProvider != null) dsL_Object_RefItemProvider.dispose();
		if (dsL_Expression_NegateItemProvider != null) dsL_Expression_NegateItemProvider.dispose();
	}

}
