/*
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SensinactUiModule extends org.eclipse.sensinact.studio.language.ui.AbstractSensinactUiModule {
	public SensinactUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
