/*
* generated by Xtext
*/
package org.eclipse.sensinact.studio.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.sensinact.studio.language.services.SensinactGrammarAccess;

public class SensinactParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SensinactGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.sensinact.studio.language.parser.antlr.internal.InternalSensinactParser createParser(XtextTokenStream stream) {
		return new org.eclipse.sensinact.studio.language.parser.antlr.internal.InternalSensinactParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Sensinact";
	}
	
	public SensinactGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SensinactGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
