/*
* generated by Xtext
*/
package org.eclipse.sensinact.studio.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SensinactAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/sensinact/studio/language/parser/antlr/internal/InternalSensinact.tokens");
	}
}
