/*
* generated by Xtext
*/
package org.eclipse.sensinact.studio.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SensinactUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.sensinact.studio.language.ui.internal.SensinactActivator.getInstance().getInjector("org.eclipse.sensinact.studio.language.Sensinact");
	}
	
}
