/**
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class SensinactQuickfixProvider extends DefaultQuickfixProvider {
}
