/**
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language.validation;

import org.eclipse.sensinact.studio.language.validation.AbstractSensinactValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SensinactValidator extends AbstractSensinactValidator {
}
