/*
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.sensinact.studio.language.ui.internal.SensinactActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SensinactExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SensinactActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SensinactActivator.getInstance().getInjector(SensinactActivator.ORG_ECLIPSE_SENSINACT_STUDIO_LANGUAGE_SENSINACT);
	}
	
}
