/*
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSensinactValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.sensinact.studio.language.sensinact.SensinactPackage.eINSTANCE);
		return result;
	}
}
