/*
* generated by Xtext
*/
package org.eclipse.sensinact.studio.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SensinactStandaloneSetup extends SensinactStandaloneSetupGenerated{

	public static void doSetup() {
		new SensinactStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

