/*
 * generated by Xtext
 */
package org.eclipse.sensinact.studio.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SensinactRuntimeModule extends org.eclipse.sensinact.studio.language.AbstractSensinactRuntimeModule {

}
